In [44]:
# Importing required libaries:
import pandas as pd
import numpy as np

In [45]:
# Opening the CSV file:
df = pd.read_csv('/content/drive/MyDrive/accident_data.csv')
df.head(10)

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200701BS64157,Serious,05-06-2019,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car
1,200701BS65737,Serious,02-07-2019,51.495029,Daylight,Kensington and Chelsea,-0.173647,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Car
2,200701BS66127,Serious,26-08-2019,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1,3,Dry,NaN,Urban,NaN,Taxi/Private hire car
3,200701BS66128,Serious,16-08-2019,51.495478,Daylight,Kensington and Chelsea,-0.202731,1,4,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
4,200701BS66837,Slight,03-09-2019,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1,2,Dry,NaN,Urban,NaN,Other vehicle
5,200701BS67159,Serious,18-09-2019,51.497750,Daylight,Kensington and Chelsea,-0.192556,2,3,Dry,Single carriageway,Urban,Fine no high winds,Car
6,200701BS67207,Serious,05-09-2019,51.501405,Daylight,Kensington and Chelsea,-0.161577,1,2,Dry,Dual carriageway,Urban,Fine no high winds,Van / Goods 3.5 tonnes mgw or under
7,200701BS67370,Fatal,03-10-2019,51.482260,Darkness - lights lit,Kensington and Chelsea,-0.179486,3,2,Dry,Single carriageway,Urban,Fine no high winds,Car
8,200701BS67515,Slight,31-10-2019,51.493319,Darkness - lights lit,Kensington and Chelsea,-0.173572,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car
9,200701BS67543,Slight,18-10-2019,51.484539,Daylight,Kensington and Chelsea,-0.175651,1,2,Dry,Single carriageway,Urban,Fine no high winds,Motorcycle over 125cc and up to 500cc

In [46]:
# Checking Rows and columns:
print(f"Rows: {df.shape[0]} \nColumns: {df.shape[1]}")

Rows: 670679
Columns: 14

In [47]:
# Making a copy of dataset:
df_clean = df.copy()

In [48]:
# Checking column names:
print(df_clean.columns)

# Converting into simple and usable forms:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.replace(' ', '_')
    .str.lower()
)

# ---FIXED---
print("\n----FIXED----\n")
print(df_clean.columns)

Index(['Index', 'Accident_Severity', 'Accident Date', 'Latitude',
       'Light_Conditions', 'District Area', 'Longitude',
       'Number_of_Casualties', 'Number_of_Vehicles', 'Road_Surface_Conditions',
       'Road_Type', 'Urban_or_Rural_Area', 'Weather_Conditions',
       'Vehicle_Type'],
      dtype='object')

----FIXED----

Index(['index', 'accident_severity', 'accident_date', 'latitude',
       'light_conditions', 'district_area', 'longitude',
       'number_of_casualties', 'number_of_vehicles', 'road_surface_conditions',
       'road_type', 'urban_or_rural_area', 'weather_conditions',
       'vehicle_type'],
      dtype='object')

In [49]:
# Checking information of dataset
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670679 entries, 0 to 670678
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   index                    670679 non-null  object
 1   accident_severity        670679 non-null  object
 2   accident_date            670679 non-null  object
 3   latitude                 670654 non-null  float64
 4   light_conditions         670679 non-null  object
 5   district_area            670679 non-null  object
 6   longitude                670653 non-null  float64
 7   number_of_casualties     670679 non-null  int64
 8   number_of_vehicles       670679 non-null  int64
 9   road_surface_conditions  669937 non-null  object
 10  road_type                666099 non-null  object
 11  urban_or_rural_area      670664 non-null  object
 12  weather_conditions       656328 non-null  object
 13  vehicle_type             670679 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 71.6+ MB

In [50]:
# Changing 'accident_date' Dtype from 'object' to 'date time'

df_clean['accident_date'] = pd.to_datetime(df_clean['accident_date'], format="%d-%m-%Y")

In [51]:
# Checking Null values percentages :
null_value_pct = df_clean.isnull().mean() * 100
print(null_value_pct[null_value_pct > 0])

latitude                   0.003728
longitude                  0.003877
road_surface_conditions    0.110634
road_type                  0.682890
urban_or_rural_area        0.002237
weather_conditions         2.139772
dtype: float64

# Handling Null Values

1. Some columns, such as `latitude`, `longitude` and `urban_or_rural_area`, contain
   only a few null values (fewer than 30 rows in total). Since this is a tiny fraction
   of the dataset, I will drop those rows, as doing so will not affect the analysis.

2. Other columns, such as `road_surface_conditions`, `road_type` and
   `weather_conditions`, contain a larger number of null values. I will not drop
   these rows, as that would mean losing useful data. Instead, I will fill the
   missing values with a separate category called "Unknown".

In [52]:
# Dropping rows:
df_clean = df_clean.dropna(subset=['latitude', 'longitude', 'urban_or_rural_area'])

# making seprate category:
for col in ['road_surface_conditions', 'road_type', 'weather_conditions']:
    df_clean[col] = df_clean[col].fillna('Unknown')

df_clean.isnull().sum()

index                      0
accident_severity          0
accident_date              0
latitude                   0
light_conditions           0
district_area              0
longitude                  0
number_of_casualties       0
number_of_vehicles         0
road_surface_conditions    0
road_type                  0
urban_or_rural_area        0
weather_conditions         0
vehicle_type               0
dtype: int64

In [53]:
# Checking duplicates:
print(f"Duplicates rows count{df_clean.duplicated().sum()}")

print("\n----Duplicates rows----\n")
dups = df_clean[df_clean.duplicated(keep=False)]
print(dups.sort_values(list(df_clean.columns)).head(20))

Duplicates rows count19

----Duplicates rows----

           index accident_severity accident_date   latitude  \
104175  2.01E+12            Slight    2019-06-27  52.647531
104225  2.01E+12            Slight    2019-06-27  52.647531
166632  2.01E+12            Slight    2019-08-31  51.478980
166633  2.01E+12            Slight    2019-08-31  51.478980
138810  2.01E+12            Slight    2019-10-05  51.360055
138811  2.01E+12            Slight    2019-10-05  51.360055
53085   2.01E+12            Slight    2019-10-18  53.970341
53086   2.01E+12            Slight    2019-10-18  53.970341
341435  2.01E+12            Slight    2020-02-21  57.441143
341436  2.01E+12            Slight    2020-02-21  57.441143
234885  2.01E+12            Slight    2020-03-04  53.742266
234895  2.01E+12            Slight    2020-03-04  53.742266
344841  2.01E+12            Slight    2020-04-05  55.988302
344844  2.01E+12            Slight    2020-04-05  55.988302
301472  2.01E+12            Slight    2020-05-03  51.015531
301473  2.01E+12            Slight    2020-05-03  51.015531
316651  2.01E+12            Slight    2020-07-30  50.853668
316652  2.01E+12            Slight    2020-07-30  50.853668
317562  2.01E+12            Slight    2020-10-11  50.868968
317576  2.01E+12            Slight    2020-10-11  50.868968

              light_conditions      district_area  longitude  \
104175                Daylight     Great Yarmouth   1.727655
104225                Daylight     Great Yarmouth   1.727655
166632                Daylight           Bridgend  -3.703668
166633                Daylight           Bridgend  -3.703668
138810                Daylight             Thanet   1.407403
138811                Daylight             Thanet   1.407403
53085                 Daylight          Harrogate  -1.405573
53086                 Daylight          Harrogate  -1.405573
341435  Darkness - no lighting      Aberdeenshire  -2.779445
341436  Darkness - no lighting      Aberdeenshire  -2.779445
234885                Daylight           Kirklees  -1.675196
234895                Daylight           Kirklees  -1.675196
344841                Daylight       East Lothian  -2.527800
344844                Daylight       East Lothian  -2.527800
301472                Daylight         Winchester  -1.341631
301473                Daylight         Winchester  -1.341631
316651                Daylight              Lewes   0.082359
316652                Daylight              Lewes   0.082359
317562                Daylight  Brighton and Hove  -0.147632
317576                Daylight  Brighton and Hove  -0.147632

        number_of_casualties  number_of_vehicles road_surface_conditions  \
104175                     1                   2                     Dry
104225                     1                   2                     Dry
166632                     1                   1                     Dry
166633                     1                   1                     Dry
138810                     1                   2                     Dry
138811                     1                   2                     Dry
53085                      1                   2                     Dry
53086                      1                   2                     Dry
341435                     2                   2                     Dry
341436                     2                   2                     Dry
234885                     1                   2                     Dry
234895                     1                   2                     Dry
344841                     1                   1                    Snow
344844                     1                   1                    Snow
301472                     1                   3                     Dry
301473                     1                   3                     Dry
316651                     1                   2                     Dry
316652                     1                   2                     Dry
317562                     1                   2             Wet or damp
317576                     1                   2             Wet or damp

                 road_type urban_or_rural_area  weather_conditions  \
104175          Roundabout               Urban  Fine no high winds
104225          Roundabout               Urban  Fine no high winds
166632  Single carriageway               Urban             Unknown
166633  Single carriageway               Urban             Unknown
138810          Roundabout               Urban  Fine no high winds
138811          Roundabout               Urban  Fine no high winds
53085   Single carriageway               Rural               Other
53086   Single carriageway               Rural               Other
341435  Single carriageway               Rural   Fine + high winds
341436  Single carriageway               Rural   Fine + high winds
234885    Dual carriageway               Rural  Fine no high winds
234895    Dual carriageway               Rural  Fine no high winds
344841    Dual carriageway               Rural               Other
344844    Dual carriageway               Rural               Other
301472    Dual carriageway               Rural  Fine no high winds
301473    Dual carriageway               Rural  Fine no high winds
316651  Single carriageway               Rural  Fine no high winds
316652  Single carriageway               Rural  Fine no high winds
317562    Dual carriageway               Rural  Fine no high winds
317576    Dual carriageway               Rural  Fine no high winds

       vehicle_type
104175          Car
104225          Car
166632          Car
166633          Car
138810          Car
138811          Car
53085           Car
53086           Car
341435          Car
341436          Car
234885          Car
234895          Car
344841          Car
344844          Car
301472          Car
301473          Car
316651          Car
316652          Car
317562          Car
317576          Car

# Handling Duplicate Values

The dataset contained 19 fully duplicated rows.
Since these are exact copies, I dropped them to avoid double-counting accidents.

In [54]:
# Dropping duplicates:
df_clean = df_clean.drop_duplicates()

# Latiitude/Longitude Validity checking:

In UK,
Latitude is generally vary  49.5 to 61.
Longitude is genrally vary -8 to 2

So, I need to check and varify latitude/longitude is real in dataset?

In [64]:
# Latitude and longitude validity:

# -- How data looks?
print(df_clean[['latitude', 'longitude']].describe())

# -- Checking zero values:
print("\nLatitude: 0 =>", (df_clean['latitude'] == 0).sum())
print("\nLongitude: 0 =>", (df_clean['longitude'] == 0).sum())

# -- Counting rows outside from UK range:
valid_mask = (
    df_clean['latitude'].between(49, 61) &
    df_clean['longitude'].between(-9, 2)
)

valid_rows = df_clean[valid_mask]
invalid_rows = df_clean[~valid_mask]

print("\nValid rows:", len(valid_rows))
print("\nInvalid rows:", len(invalid_rows))

"""
In this dataset, there are no invlalid rows available.
So, I skip it now and move to next
"""

            latitude      longitude
count  670632.000000  670632.000000
mean       52.554002      -1.431464
std         1.406938       1.383207
min        49.914430      -7.516225
25%        51.490674      -2.332398
50%        52.316358      -1.411801
75%        53.453393      -0.233366
max        60.757544       1.762010

Latitude: 0 => 0

Longitude: 0 => 0

Valid rows: 670632

Invalid rows: 0

In [65]:
# Severity column checking:
severity_col = df_clean['accident_severity'].value_counts()
print(severity_col)

accident_severity
Slight     572265
Serious     89563
Fatal        8804
Name: count, dtype: int64

In [66]:
# Exporting a new cleaned file:
df_clean.to_parquet('cleaned_accident_data.parquet', index=False)